# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'ado-sonarcloud-connection'
    organization: 'mohit11100348'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Mohit11100348_ado-sonarqube-integration'
    cliProjectName: 'ado-sonarqube-integration'
    cliSources: '.'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SonarCloudAnalyze@1