# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ImageName: 'mohit1110/microservicedemo:$(Build.BuildId)'

steps:
#- task: NodeTool@0
#  inputs:
#    versionSpec: '12.x'
#  displayName: 'Install Node.js'

#- script: |
#    npm install
#  displayName: 'npm install'

- task: Docker@1
  displayName: 'Build the Docker image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Build an image'
    dockerFile: '**/Dockerfile'
    imageName: '$(ImageName)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '.'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'ado-sonarcloud-connection'
    organization: 'mohit11100348'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Mohit11100348_ado-sonarqube-integration'
    cliProjectName: 'ado-sonarqube-integration'
    cliSources: '.'

- script: |
    npm run build
  displayName: 'npm build'

- task: SonarCloudAnalyze@1